name: Run Selenium Java application built with Maven

on:
  push:
    branches:
      - master # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - master

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest
    if: always()

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      # Step 3: Set up Chrome browser (pre-installed on GitHub runners)
      - name: Set up Chrome browser
        run: google-chrome --version

      # Step 4: Cache Maven dependencies (improves build times)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Install dependencies with Maven
      - name: Build with Maven
        run: mvn install

      # Step 6: Run Selenium script using Maven and Send Telegram notification
      - name: Run Selenium script & Notify via Telegram
        run: |
          mvn exec:java -Dexec.mainClass="eclass.kr.DeadlineNotifier" > OUTPUT.txt
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$(sed -n '/We/,/^\[Warning]/p' OUTPUT.txt)"
        env:
          ID: ${{ secrets.ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
